POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "jim",
  "password": "jim"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "Tommy",
  "password": "Tommy"
}

###

POST http://localhost:5000/api/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ5NTAyMTUzNGQyZjAwMTZkNzJhMTQiLCJpYXQiOjE2MzIyNzY5MTR9.54Bf93j94_JFQMwWr5q9lLKhI5KOjDHKGeo1DhpybRU

{
  "title": "React",
  "content": "React",
  "attachment": "",
  "likeCount": "0"  
}

###

GET http://localhost:5000/api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTQ5NTAyMTUzNGQyZjAwMTZkNzJhMTQiLCJpYXQiOjE2MzIyNzY5MTR9.54Bf93j94_JFQMwWr5q9lLKhI5KOjDHKGeo1DhpybRU
###

PUT http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA

{
  "title": "Vue",
  "description": "VUEEEEE",
  "url": "https://vuejs.org",
  "status": "LEARNING"
}

###

DELETE http://localhost:5000/api/posts/6061c25ac2533d41dcae2b19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MDYxYjk1YjdkMjljZTFiMTA5YmQxZTAiLCJpYXQiOjE2MTcwMTk3ODF9.ri-nHdgZc1VQTocFLfMgF4_PhFf2TeUVqXLd8tpOkeA
